
const constants ={
    ADD_TO_BASKET: "ADD_TO_BASKET",
    SET_USER :"SET_USER",
    EMPTY_BASKET: "EMPTY_BASKET",
    SELECT_ADD :"SELECT_ADD",
    SELECT_DELETE :"SELECT_DELETE",
    SLECT_UPDATE :"SLECT_UPDATE",
    SELECT_SEARCH :"SELECT_SEARCH",
    SELECT_ALL_STUDENTS :"SELECT_ALL_STUDENTS",
    SELECT_TAB :"SELECT_TAB",


}
export default constants;